# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CadenceTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CadenceTest
  pod 'AntPlusPlugins'

  target 'CadenceTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CadenceTestUITests' do
    # Pods for testing
  end

end
